{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.4.jar",
          "url": "process-worker-plugin-gradle-1.0.4.jar",
          "size": 30326,
          "sha512": "e41b48c67f5b5e200aba7b89a43c40cdc4b3a51d42bd92d45fc396297300fcba9b3c63ba3fa8d2666656ee0e0928e6c680f9c790269d83c719247e441956146e",
          "sha256": "360ef8747bd561eb51e908110df2f19275a7f91e44699c0b4c957f6c21a8b7c0",
          "sha1": "5cd6916236bbb1d2427afe9c00ed49383c84d4cf",
          "md5": "aae4391569b8617d84e28c761637d3c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.4.jar",
          "url": "process-worker-plugin-gradle-1.0.4.jar",
          "size": 30326,
          "sha512": "e41b48c67f5b5e200aba7b89a43c40cdc4b3a51d42bd92d45fc396297300fcba9b3c63ba3fa8d2666656ee0e0928e6c680f9c790269d83c719247e441956146e",
          "sha256": "360ef8747bd561eb51e908110df2f19275a7f91e44699c0b4c957f6c21a8b7c0",
          "sha1": "5cd6916236bbb1d2427afe9c00ed49383c84d4cf",
          "md5": "aae4391569b8617d84e28c761637d3c5"
        }
      ]
    }
  ]
}
