{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.4.jar",
          "url": "process-worker-plugin-gradle-1.0.4.jar",
          "size": 30326,
          "sha512": "1ee4ac5667063fe53475588c5b07a3cf0e3f068001a371b49f0efa980bf67c039aab3291baec0da0083b1df2aed3de9fead57e83727632d4299266743a98484e",
          "sha256": "34be18b2e9f86bb6650f02b9009c3183a5e18713353d4a444327cb9aa3f24ca7",
          "sha1": "fbcf19fc210bba227bcc8ddc28428e95b9ba74ab",
          "md5": "1a43126e0b508adf6a84c195c0c14075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.4.jar",
          "url": "process-worker-plugin-gradle-1.0.4.jar",
          "size": 30326,
          "sha512": "1ee4ac5667063fe53475588c5b07a3cf0e3f068001a371b49f0efa980bf67c039aab3291baec0da0083b1df2aed3de9fead57e83727632d4299266743a98484e",
          "sha256": "34be18b2e9f86bb6650f02b9009c3183a5e18713353d4a444327cb9aa3f24ca7",
          "sha1": "fbcf19fc210bba227bcc8ddc28428e95b9ba74ab",
          "md5": "1a43126e0b508adf6a84c195c0c14075"
        }
      ]
    }
  ]
}
