{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.2.jar",
          "url": "process-worker-plugin-gradle-1.0.2.jar",
          "size": 20973,
          "sha512": "6e9a23c91e8a7f64e2bee3958a122eff64b0dbfeb555e9ea4bf3bb0387475d6df88cd978aee59d9e55df3fc163a410076711e35eaac5fe34a458fdd2bfe8430d",
          "sha256": "db6af23158cf07465c8eab385bdf31ba45e54223c37de8dbc97059d37419efa5",
          "sha1": "228da90c8a1e2360cff22a3a6988da94758cecd4",
          "md5": "7c9a6db8d3fa8027db2d056835731089"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.2.jar",
          "url": "process-worker-plugin-gradle-1.0.2.jar",
          "size": 20973,
          "sha512": "6e9a23c91e8a7f64e2bee3958a122eff64b0dbfeb555e9ea4bf3bb0387475d6df88cd978aee59d9e55df3fc163a410076711e35eaac5fe34a458fdd2bfe8430d",
          "sha256": "db6af23158cf07465c8eab385bdf31ba45e54223c37de8dbc97059d37419efa5",
          "sha1": "228da90c8a1e2360cff22a3a6988da94758cecd4",
          "md5": "7c9a6db8d3fa8027db2d056835731089"
        }
      ]
    }
  ]
}
