{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.2.jar",
          "url": "process-worker-plugin-gradle-1.0.2.jar",
          "size": 21251,
          "sha512": "ce0956dbc46207ea4b4bc95afcbae883bf22e11370c66ca7cb44a6b6503296f687a690ebd95b13f1f178af556bb204fa0f2e499a28846e51d856d93704edc6d9",
          "sha256": "05fb68169ed435f13ce087166bce3f7fc39aa628e499fb9588df872d755f79b3",
          "sha1": "5fab808c864fb83a36febdd5e5fb5f774307ab76",
          "md5": "654ac4ee7832a8a113c381ce32d52b3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.2.jar",
          "url": "process-worker-plugin-gradle-1.0.2.jar",
          "size": 21251,
          "sha512": "ce0956dbc46207ea4b4bc95afcbae883bf22e11370c66ca7cb44a6b6503296f687a690ebd95b13f1f178af556bb204fa0f2e499a28846e51d856d93704edc6d9",
          "sha256": "05fb68169ed435f13ce087166bce3f7fc39aa628e499fb9588df872d755f79b3",
          "sha1": "5fab808c864fb83a36febdd5e5fb5f774307ab76",
          "md5": "654ac4ee7832a8a113c381ce32d52b3c"
        }
      ]
    }
  ]
}
