{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.2.jar",
          "url": "process-worker-plugin-gradle-1.0.2.jar",
          "size": 21251,
          "sha512": "a8894d1b943159ccc6f308ad299b6d378897e3e88a6827950207bcf465d569d87e5ae272bb9b7374d696d620a9a5eb131ea594ec319e1e88154ebbad22d3eb8c",
          "sha256": "76583fabad56e4392087357110de90086c01d342572a32a62ee724da8fda03e9",
          "sha1": "1fa171c4e54d7313ffe95a50a553d48a6f37d5cf",
          "md5": "93d5b713155283ee6d321d12f13ec813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.2.jar",
          "url": "process-worker-plugin-gradle-1.0.2.jar",
          "size": 21251,
          "sha512": "a8894d1b943159ccc6f308ad299b6d378897e3e88a6827950207bcf465d569d87e5ae272bb9b7374d696d620a9a5eb131ea594ec319e1e88154ebbad22d3eb8c",
          "sha256": "76583fabad56e4392087357110de90086c01d342572a32a62ee724da8fda03e9",
          "sha1": "1fa171c4e54d7313ffe95a50a553d48a6f37d5cf",
          "md5": "93d5b713155283ee6d321d12f13ec813"
        }
      ]
    }
  ]
}
