JDBC_URL=jdbc:postgresql://localhost:15432/kramerius
JDBC_USERNAME=fedoraAdmin
JDBC_PASSWORD=fedoraAdmin
#JDBC_POOL_MAX_SIZE=10
#JDBC_POOL_CONNECTION_TIMEOUT_MS=10000
#JDBC_POOL_VALIDATION_TIMEOUT_MS=5000
#JDBC_POOL_IDLE_TIMEOUT_MS=300000
#JDBC_POOL_MAX_LIFETIME_MS=1500000
#JDBC_POOL_KEEPALIVE_TIME_MS=120000
#HTTP_CLIENT_MAX_CONNECTIONS=20
#HTTP_CLIENT_MAX_CONNECTIONS_PER_ROUTE=10
#HTTP_CLIENT_CONNECT_TIMEOUT_MS=10000
#HTTP_CLIENT_SOCKET_TIMEOUT_MS=60000
#HTTP_CLIENT_CONNECTION_REQUEST_TIMEOUT_MS=10000
#HTTP_CLIENT_RESPONSE_TIMEOUT_MS=60000
#HTTP_CLIENT_VALIDATE_AFTER_INACTIVITY_MS=10000
#HTTP_CLIENT_EVICT_IDLE_CONNECTIONS_MS=30000
#NEXT_SCHEDULED_PROCESS_STRATEGY=TAG_MATCHING_ONLY
#NEXT_SCHEDULED_PROCESS_STRATEGY=BATCH_AFFINITY
