{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.3.jar",
          "url": "process-worker-plugin-gradle-1.0.3.jar",
          "size": 23002,
          "sha512": "fd49437816eaa447c8ee46e1da524bfc76ce7a088916e427a5947496c940cddb276535c0f25fb58e6b6fd3ba7d3c002bb2b0d8de087f0dcd9f77de2dd871dc7a",
          "sha256": "083f3b74276e1771b2b307822825adb286b4121118333470eb3b48e58717aa4f",
          "sha1": "930caeca7c3e655c25e60424785638c085b03e82",
          "md5": "5d5f89f72cf1182c55bb08e22833959b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.3.jar",
          "url": "process-worker-plugin-gradle-1.0.3.jar",
          "size": 23002,
          "sha512": "fd49437816eaa447c8ee46e1da524bfc76ce7a088916e427a5947496c940cddb276535c0f25fb58e6b6fd3ba7d3c002bb2b0d8de087f0dcd9f77de2dd871dc7a",
          "sha256": "083f3b74276e1771b2b307822825adb286b4121118333470eb3b48e58717aa4f",
          "sha1": "930caeca7c3e655c25e60424785638c085b03e82",
          "md5": "5d5f89f72cf1182c55bb08e22833959b"
        }
      ]
    }
  ]
}
