{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.1.jar",
          "url": "process-plugin-gradle-1.0.1.jar",
          "size": 22441,
          "sha512": "54b4733be8c7e198287f6f51772bf1b2bd1f8dc2f09390f895b593ed94bb8067d2680ebf54bcd4af4f97d84ec16170ab349809e7ac077a22434d88cf40f27628",
          "sha256": "a6019b4ec63398a25b4c7ce266fa70dd1e430298c40431d6237579f657ceb105",
          "sha1": "b6a83c9cf8f4d52a981a8080f49f233ccf36ac59",
          "md5": "a2a3dc24bd9ff8fff91a8ef821a69d42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.1.jar",
          "url": "process-plugin-gradle-1.0.1.jar",
          "size": 22441,
          "sha512": "54b4733be8c7e198287f6f51772bf1b2bd1f8dc2f09390f895b593ed94bb8067d2680ebf54bcd4af4f97d84ec16170ab349809e7ac077a22434d88cf40f27628",
          "sha256": "a6019b4ec63398a25b4c7ce266fa70dd1e430298c40431d6237579f657ceb105",
          "sha1": "b6a83c9cf8f4d52a981a8080f49f233ccf36ac59",
          "md5": "a2a3dc24bd9ff8fff91a8ef821a69d42"
        }
      ]
    }
  ]
}
