MANAGER_BASE_URL=-none-
WORKER_BASE_URL=-none-
WORKER_ID=-none-
WORKER_LOOP_SLEEP_SECS=0.3
WORKER_LOOP_PRINT_SECS=30
#HTTP_CLIENT_MAX_CONNECTIONS=20
#HTTP_CLIENT_MAX_CONNECTIONS_PER_ROUTE=10
#HTTP_CLIENT_CONNECT_TIMEOUT_MS=10000
#HTTP_CLIENT_SOCKET_TIMEOUT_MS=60000
#HTTP_CLIENT_CONNECTION_REQUEST_TIMEOUT_MS=10000
#HTTP_CLIENT_RESPONSE_TIMEOUT_MS=60000
#HTTP_CLIENT_VALIDATE_AFTER_INACTIVITY_MS=10000
#HTTP_CLIENT_EVICT_IDLE_CONNECTIONS_MS=30000
#PROFILES_SUBSET=profile1,profile2
