{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.5.jar",
          "url": "process-worker-plugin-gradle-1.0.5.jar",
          "size": 36094,
          "sha512": "8b8e83441ca6b977500a698dd787c3f632cb6b910d797a7d7e00f68b19d8f1bc97d82d749d0bf79f684fdf66308aa50123c19da578ea9b4bd0671fcda9651c08",
          "sha256": "4d36903d3b13ca594addff4e1b84884cd2c9dfe92c72028d84e77f6d08b7ee49",
          "sha1": "ebf60ea5da19ebfa50a84f9900bcbcd406e44844",
          "md5": "951e6a3fec935c230ada42814b790307"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.5.jar",
          "url": "process-worker-plugin-gradle-1.0.5.jar",
          "size": 36094,
          "sha512": "8b8e83441ca6b977500a698dd787c3f632cb6b910d797a7d7e00f68b19d8f1bc97d82d749d0bf79f684fdf66308aa50123c19da578ea9b4bd0671fcda9651c08",
          "sha256": "4d36903d3b13ca594addff4e1b84884cd2c9dfe92c72028d84e77f6d08b7ee49",
          "sha1": "ebf60ea5da19ebfa50a84f9900bcbcd406e44844",
          "md5": "951e6a3fec935c230ada42814b790307"
        }
      ]
    }
  ]
}
