{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-worker-plugin-gradle",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.5.jar",
          "url": "process-worker-plugin-gradle-1.0.5.jar",
          "size": 42855,
          "sha512": "cdd8063bbd98295b7c1cfc623e5f4b3ae407b5f8aca5cccf3ebd5dc8f8b1a3c1642e1d2b5689812f30ce3c1150432fba3455c9bfaa1e36e3c37e3db6344c3d34",
          "sha256": "837f245122aff2cc7582766e5d13600b1d253006dd35e5c230295e26a2e64021",
          "sha1": "cb98358d81199c7c4612ed709da65023c8b2d4ef",
          "md5": "1530ad94bba57410ca402cc294f45178"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-worker-plugin-gradle-1.0.5.jar",
          "url": "process-worker-plugin-gradle-1.0.5.jar",
          "size": 42855,
          "sha512": "cdd8063bbd98295b7c1cfc623e5f4b3ae407b5f8aca5cccf3ebd5dc8f8b1a3c1642e1d2b5689812f30ce3c1150432fba3455c9bfaa1e36e3c37e3db6344c3d34",
          "sha256": "837f245122aff2cc7582766e5d13600b1d253006dd35e5c230295e26a2e64021",
          "sha1": "cb98358d81199c7c4612ed709da65023c8b2d4ef",
          "md5": "1530ad94bba57410ca402cc294f45178"
        }
      ]
    }
  ]
}
