{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.3.jar",
          "url": "process-plugin-gradle-1.0.3.jar",
          "size": 32023,
          "sha512": "aed38cc4d492f7295451fc29511f400ba934563cbd11f23f1cd44a125ef1e1e11f87d393bfd5e0eaf62f480115989107d738a6df7c5b7eb53a6970eb91a6d504",
          "sha256": "1afdd3046b97780ebdfde660d09f930b9c77928f5d27773752611be0f5ce0a58",
          "sha1": "3f63e56f1b78beac03cae850e6b58c255858e21c",
          "md5": "1693347b146f0212b768b8a9da16c439"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.3.jar",
          "url": "process-plugin-gradle-1.0.3.jar",
          "size": 32023,
          "sha512": "aed38cc4d492f7295451fc29511f400ba934563cbd11f23f1cd44a125ef1e1e11f87d393bfd5e0eaf62f480115989107d738a6df7c5b7eb53a6970eb91a6d504",
          "sha256": "1afdd3046b97780ebdfde660d09f930b9c77928f5d27773752611be0f5ce0a58",
          "sha1": "3f63e56f1b78beac03cae850e6b58c255858e21c",
          "md5": "1693347b146f0212b768b8a9da16c439"
        }
      ]
    }
  ]
}
