{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.5.jar",
          "url": "process-plugin-gradle-1.0.5.jar",
          "size": 35825,
          "sha512": "6ad6712dce95fc612a5a263f721cf99b93ce92d9f914e5152327246204a0138059de2481c7e82c7d2cf79e23496ccf1a566b259d1df3d9792121872a21ba823a",
          "sha256": "f2bdb340335d2802207117774425ee14908e9647cfe0a979d64bad7432d7c20f",
          "sha1": "e8d0a3de2e4303b48fd0cc79615ede087773ff58",
          "md5": "d7bc1e2003ed7729a9b18487d9ec034c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.5.jar",
          "url": "process-plugin-gradle-1.0.5.jar",
          "size": 35825,
          "sha512": "6ad6712dce95fc612a5a263f721cf99b93ce92d9f914e5152327246204a0138059de2481c7e82c7d2cf79e23496ccf1a566b259d1df3d9792121872a21ba823a",
          "sha256": "f2bdb340335d2802207117774425ee14908e9647cfe0a979d64bad7432d7c20f",
          "sha1": "e8d0a3de2e4303b48fd0cc79615ede087773ff58",
          "md5": "d7bc1e2003ed7729a9b18487d9ec034c"
        }
      ]
    }
  ]
}
