{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.5.jar",
          "url": "process-plugin-gradle-1.0.5.jar",
          "size": 36004,
          "sha512": "58feadd1ea3d45db56364de23269c7036f67ef5f3cca6575c9aed72a5794ae9b3dad5869182beec4c9b43423230f63360290c275eebb4e7efe57e55368022beb",
          "sha256": "4e82b171651d21069e3710463fcb70bce40a0615bbd4019be19350f5b7f1927f",
          "sha1": "fb1fec20e2d3c39f258b24dbc8e588a4d4588d89",
          "md5": "7392d050207403e011c16488a4b1ea8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.5.jar",
          "url": "process-plugin-gradle-1.0.5.jar",
          "size": 36004,
          "sha512": "58feadd1ea3d45db56364de23269c7036f67ef5f3cca6575c9aed72a5794ae9b3dad5869182beec4c9b43423230f63360290c275eebb4e7efe57e55368022beb",
          "sha256": "4e82b171651d21069e3710463fcb70bce40a0615bbd4019be19350f5b7f1927f",
          "sha1": "fb1fec20e2d3c39f258b24dbc8e588a4d4588d89",
          "md5": "7392d050207403e011c16488a4b1ea8d"
        }
      ]
    }
  ]
}
