{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.0.jar",
          "url": "process-plugin-gradle-1.0.0.jar",
          "size": 16757,
          "sha512": "b70f38924e3245dc87cc395e876c72af5205237f4245b670286bda1e1b4453e6094cab63f90450a0e093614c0d45d1b57752a602be4f862d5111f9d6abb7c0e4",
          "sha256": "08a24ccc3a805f9361210df23a37f894f16d9e431cae4ce3641eb54cfdaef604",
          "sha1": "fc1dee8945952bdefe4c11d98c5a27278fa32a4d",
          "md5": "1b3deb8c25f918794cafa8d7b2001f38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.0.jar",
          "url": "process-plugin-gradle-1.0.0.jar",
          "size": 16757,
          "sha512": "b70f38924e3245dc87cc395e876c72af5205237f4245b670286bda1e1b4453e6094cab63f90450a0e093614c0d45d1b57752a602be4f862d5111f9d6abb7c0e4",
          "sha256": "08a24ccc3a805f9361210df23a37f894f16d9e431cae4ce3641eb54cfdaef604",
          "sha1": "fc1dee8945952bdefe4c11d98c5a27278fa32a4d",
          "md5": "1b3deb8c25f918794cafa8d7b2001f38"
        }
      ]
    }
  ]
}
