{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.0.jar",
          "url": "process-plugin-gradle-1.0.0.jar",
          "size": 16757,
          "sha512": "64fe5d01af2f21a8495c9d0d7f4d0115ced65176362fed30ad6240c4f749c78117963ccef1c53a828208609b5b2392ae067069b1c2437579fee367f240057dab",
          "sha256": "7b5cb3d8cd08dfdd89d3dbfa06ac5e80c30a231b93fa68bc4c462433380c888a",
          "sha1": "8e108f8db3f5ad374c419e2278dea58fbf792982",
          "md5": "e2947e02c2044f5b935c661a5a2c7a91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.0.jar",
          "url": "process-plugin-gradle-1.0.0.jar",
          "size": 16757,
          "sha512": "64fe5d01af2f21a8495c9d0d7f4d0115ced65176362fed30ad6240c4f749c78117963ccef1c53a828208609b5b2392ae067069b1c2437579fee367f240057dab",
          "sha256": "7b5cb3d8cd08dfdd89d3dbfa06ac5e80c30a231b93fa68bc4c462433380c888a",
          "sha1": "8e108f8db3f5ad374c419e2278dea58fbf792982",
          "md5": "e2947e02c2044f5b935c661a5a2c7a91"
        }
      ]
    }
  ]
}
