{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.2.jar",
          "url": "process-plugin-gradle-1.0.2.jar",
          "size": 32128,
          "sha512": "33c337373d803d45ff2ac2c138dcde099c2dee61b8146945220ef882cfbfae7f8ad58cdbea830d5fffb5dfa79b46bc5748d7bb33656e21e3f283036f7d491240",
          "sha256": "0823d02b91a5bcc8d6c8d19522ef20f0edaedd0d6fd89e34cd2e6728cc61caed",
          "sha1": "3ba14dfdb485ebc3d3547a7c87a5168b0c7e35f5",
          "md5": "2b1f76be0afa7c50ba80149bff79e0e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.2.jar",
          "url": "process-plugin-gradle-1.0.2.jar",
          "size": 32128,
          "sha512": "33c337373d803d45ff2ac2c138dcde099c2dee61b8146945220ef882cfbfae7f8ad58cdbea830d5fffb5dfa79b46bc5748d7bb33656e21e3f283036f7d491240",
          "sha256": "0823d02b91a5bcc8d6c8d19522ef20f0edaedd0d6fd89e34cd2e6728cc61caed",
          "sha1": "3ba14dfdb485ebc3d3547a7c87a5168b0c7e35f5",
          "md5": "2b1f76be0afa7c50ba80149bff79e0e4"
        }
      ]
    }
  ]
}
