{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ceskaexpedice.processplatform",
    "module": "process-plugin-gradle",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.2.jar",
          "url": "process-plugin-gradle-1.0.2.jar",
          "size": 31773,
          "sha512": "5ea10a7d43ab92a5e9803daf42abaafa5ddb6b6f76ea61a6a79e7aafa91da009cdcdd4557791ff7fa04311796b5a55d1c9b4ad58a12c768bf11a98e17415132c",
          "sha256": "9540124fc0e31a5db3241cfbf6e1f69d72f53fe541fda0efde38c3a5070e76e4",
          "sha1": "9170469c4a5ecba3bde1d978e028828647bd3e2b",
          "md5": "813b34d4a983ecdfd09bceb87d331138"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "process-plugin-gradle-1.0.2.jar",
          "url": "process-plugin-gradle-1.0.2.jar",
          "size": 31773,
          "sha512": "5ea10a7d43ab92a5e9803daf42abaafa5ddb6b6f76ea61a6a79e7aafa91da009cdcdd4557791ff7fa04311796b5a55d1c9b4ad58a12c768bf11a98e17415132c",
          "sha256": "9540124fc0e31a5db3241cfbf6e1f69d72f53fe541fda0efde38c3a5070e76e4",
          "sha1": "9170469c4a5ecba3bde1d978e028828647bd3e2b",
          "md5": "813b34d4a983ecdfd09bceb87d331138"
        }
      ]
    }
  ]
}
